[[main],window=_blank]
== Links: September 9, 2026

https://www.propublica.org/article/fbi-susan-collins-navatek-campaign-donations-investigation[FBI
Eyed Susan Collins Over Defense Contractor’s Donations — ProPublica,window=_blank]

https://www.lawfaremedia.org/article/invisible-source-skew[Invisible
Source Skew ++|++ Lawfare,window=_blank]

https://thehill.com/homenews/campaign/6059321-el-sayed-apologizes-synagogue-response/[Abdul
El-Sayed apologizes to Jewish Democrats for synagogue attack comment,window=_blank]

https://www.chronicle.com/article/the-complacent-style-in-american-academe[The
Complacent Style in American Academe,window=_blank]

https://www.liberalcurrents.com/the-interracial-cuck-porn-theory-of-everything/[The
Interracial Cuck Porn Theory of Everything,window=_blank]

https://newrepublic.com/post/215105/el-sayed-hasan-piker-media[How to
Answer Yet Another Dumb Question About Hasan Piker ++|++ The New
Republic,window=_blank]

https://www.amazon.com/gp/product/B008DR6YXO?dplnkId=23fd31f1-a1cb-4144-9b3e-c1553f35a020&nodl=1[Amazon.com:
The Wages of Destruction: The Making and Breaking of the Nazi Economy
eBook : Tooze&#44; Adam: Kindle Store,window=_blank]

https://www.ca3.uscourts.gov/opinions-and-oral-arguments[Opinions and
Oral Arguments ++|++ Third Circuit ++|++ United States Court of Appeals,window=_blank]

https://www.nytimes.com/wirecutter/reviews/the-best-instant-read-thermometer/[The
6 Best Meat Thermometers for 2026 ++|++ Reviews by Wirecutter,window=_blank]

https://www.bostonreview.net/forum/climate-state-and-utopia/[Climate&#44;
State&#44; and Utopia - Boston Review,window=_blank]

https://www.poetryfoundation.org/poems/43290/the-second-coming[The
Second Coming ++|++ The Poetry Foundation,window=_blank]

https://www.lrb.co.uk/the-paper/v48/n17/susan-pedersen/keep-off-the-grass[Susan
Pedersen · Keep off the grass: Oxbridge Attitudes,window=_blank]

https://arcmag.org/destroy-israel-repair-the-world/[Destroy Israel&#44;
Repair the World ++|++ ARC: Religion&#44; Politics&#44; Et Cetera,window=_blank]

http://www.weasner.com/etx/reviews/2011/stanley_case/index.html[Weasner’s
Accessory Review,window=_blank]

https://www.google.com/search?q=in-ear+wired+monitors+classical&udm=14[in-ear
wired monitors classical - Google Search,window=_blank]

https://moondroplab.com/en/products/ssr[MOONDROP SSR Super Spaceship
Reference In-Ear Monitors ++|++ MOONDROP Official Website,window=_blank]

https://thepointmag.com/examined-life/getting-good-effective-altruism/[Getting
Good ++|++ The Point Magazine,window=_blank]

https://gillianbrockell.com/tracking-all-of-trumps-third-country-removals-that-we-know-of/[Tracking
All of Trump’s Known Third-Country Removals,window=_blank]

https://www.supportnow.org/barry-crain/updates/late-summer-update-part-4[Update
for Barry Crain: Late summer update (Part 4) ++|++ SupportNow.org,window=_blank]

https://newrepublic.com/article/215784/diesel-gas-prices-bury-trump-midterm-elections?utm_source=newsletter&utm_medium=email&utm_campaign=the_ticker_rss[We
Now Know the Word That’s Going to Bury Donald Trump This November ++|++
The New Republic,window=_blank]

https://www.liberalcurrents.com/democratic-socialism-gets-serious/[Democratic
Socialism Gets Serious,window=_blank]
